### ISSUE TITLE
ETA for "production-ready" state?

### ISSUE THREAD

**Issue by igorgatis** [Bobris/Nowin#22]
README says:
> Current status is usable for testing, not for production, nobody did any security review, you have been warned.

Is there any ETA for **production** level? I liked Nowin a lot. I have plans to use it in production with financial services and security is a concern.

**Comment by Bobris** [comment]
There are users which using it in production already, but I am no sure it is enough to say it is tested good enough. Finally it is your decision ...

**Comment by Bobris** [comment]
But to answer your question there is no ETA. It IMHO needs more "success" stories before I will be brave enough to remove this warning :-)
