### ISSUE TITLE
Please how do we use this to do Server-Sent Events?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [Bobris/Nowin#24]
Please can you advise on how to use this library to achieve Server-Sent Events

Thanks.

**Comment by Bobris** [comment]
Created simple example for you - it is independent to Nowin - every owin host should support it.
https://github.com/Bobris/Nowin/commit/446eb27607e214fdd78179cf413ec7e1203338b4

**Comment by CharlesOkwuagwu** [comment]
Thanks
