### ISSUE TITLE
ExecutionContext is not restored after the server is disposed

### ISSUE THREAD

**Issue by mfloryan** [Bobris/Nowin#25]
In a large test-suite where we rely on `ExecutionContext` to be able to flow we have noticed that running `Nowin` breaks our tests. We have identified the source of the problem in [SaeaLayerCallback.cs](https://github.com/Bobris/Nowin/blob/master/Nowin/SaeaLayerCallback.cs#L206).

Please consider wrapping the suppression in a using statement at the correct level so that the async methods don't flow context but the main thread can retain the context flowing for the rest of the application.

**Comment by Bobris** [comment]
I am not sure I am able to do it, because Nowin runs on ThreadPool threads and it just forbids it in each thread it finds. And cannot return to particular threads to restore flow. If you have some idea how to solve it, please tell me.

**Comment by serialseb** [comment]
I have prepared a pull request, but i need to understand better why you suppress the context flow. Is this to prevent execution flow when you call the async methods so accepting and receiving won't be in the context of the main thread?

**Comment by Bobris** [comment]
It just slow without it, all SEAE functions do a lot of allocations when Execution flow is enabled.

**Comment by serialseb** [comment]
Any script / test I could use to try a few things and see if my pull request would preserve your perf goals or if my code won't work?

**Comment by serialseb** [comment]
if not i'll write something myself, trying to cause as little work for you as possible and fix our problems :)

**Comment by serialseb** [comment]
FYI my theory here is that if you suppress the flow on calling the async methods and undo the suppression afterwards by wrapping in a using block, the call context doesn't do the capture / copy, and as such doesn't do the restore on the other side, while keeping the thread itself in the state it was found in when you exit. At the very least it means we can write a little mdidleware that would capture the context on init and restore it on the owin pipeline ourselves to flow it again in our test suite where we flow across the app.

**Comment by Bobris** [comment]
I thought about it in mean time. And you are right it could work. Just push
it and I will test it.
Dne 7. 3. 2015 11:14 "Sebastien Lambla" <notifications@github.com>
napsal(a):

**Comment by serialseb** [comment]
cool, pull request coming tomorrow then, will update when. I'm travelling so at worst monday.

**Comment by Bobris** [comment]
What about making it configurable. Would that work for you? Do you use ServerBuilder?

**Comment by serialseb** [comment]
we use serverbuilder. I'd be happy to have using around the flow if that still hits the perf targets, and in option to not do the suppress. If you're happy with .SetExecutionContextFlow(true), or maybe something aong the lines of a SetAdvancedOptions(AdvancedOtpions.FlowExecutionContext)? Let me know what you feel happy with i can update the PR before sending it :)

**Comment by Bobris** [comment]
Something like this: (maybe you can come up with better names as I am not native speaker)

     enum ExecutionContextFlowType { Disable, TemporaryDisable, DontTouchSlow }
     SetExecutionContextFlow(ExecutionContextFlowType value)

Disable would be current behaviour. TemporaryDisable is what you want. DontTouchSlow would just Don't touch Context flow at all.
Anyway thanks for help. I will do release after merging your code.

**Comment by serialseb** [comment]
cool, will prepare tomorrow and see if I can find something good.
