### ISSUE TITLE
Tests project does not build in Xamarin Studio / OSX

### ISSUE THREAD

**Issue by jchannon** [Bobris/Nowin#29]
This is because it does not understand `PushStreamContent`

**Comment by Bobris** [comment]
What would you suggest? Copy source of it locally? (was it already opensourced?)

**Comment by jchannon** [comment]
I'm not sure where the class comes from so not sure what I can suggest

**Comment by Bobris** [comment]
It is this one: 
https://msdn.microsoft.com/en-us/library/system.net.http.pushstreamcontent%28v=vs.118%29.aspx

    <Reference Include="System.Net.Http.Formatting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" />
