### ISSUE TITLE
TLS 1.2 support

### ISSUE THREAD

**Issue by et1975** [Bobris/Nowin#32]
Currently default HTTPS status as reported by Chrome labels TLS 1.0 as "obsolete cryptography", could [TLS 1.2 parameter](https://msdn.microsoft.com/en-us/library/ms145065(v=vs.110).aspx) be specified by default (or made configurable from the outside)?

**Comment by Bobris** [comment]
Done, though by default I left TLS 1.0 enabled because that's what IE9 on Win7 uses.

**Comment by et1975** [comment]
Awesome, thank you!
