### ISSUE TITLE
SSL v3 disabled in 0.16.0?

### ISSUE THREAD

**Issue by igorgatis** [Bobris/Nowin#33]
0.16.0 disabled SSL v3 by default: https://github.com/Bobris/Nowin/commit/f869c9573789ec9157e3d9858bc5797b40e1b6d5#diff-608c40426c1568b8a09cd18fa10edfcaR15

IMHO, since this break things, I'd say this deserves at least a clear announcement.

FWIW, .Net framework's default still includes SSL v3: http://referencesource.microsoft.com/#System/net/System/Net/SecureProtocols/SslEnumTypes.cs,23

**Comment by Bobris** [comment]
Yes, that's true. I really believe for security by default. I didn't really have setup any way how to notify users about these changes. If you have idea what should be best for you and easy for me I will definitely consider it.
http://disablessl3.com/

**Comment by igorgatis** [comment]
Stating that in the commit title should suffice, IMHO.

**Comment by Bobris** [comment]
Ok, I will try to describe it better next time. Thanks for input.
