### ISSUE TITLE
If ssl authentication fails we get an Object reference error

### ISSUE THREAD

**Issue by FungusHumungus** [Bobris/Nowin#41]
If eg. you pass a dodgy certificate to Nowin the call to `_ssl.AuthenticateAsServerAsync` returns with t.IsFaulted == true.

This causes the following line to run :
 
    self._next.FinishAccept(null, 0, 0, null, null);

FinishAccept then throws an ObjectReference error because localEndPoint is now null.

**Comment by Bobris** [comment]
Don't know I was thinking that would be useful for...

Could you try to replace both these lines with too many nulls with:

                        Callback.StartDisconnect();

If it solves your problem?

**Comment by FungusHumungus** [comment]
Yes that fixes the problem nicely. Many thanks.

Have submitted a Pull Request with the fix.

**Comment by Bobris** [comment]
Changed also other line. And published in nuget

**Comment by FungusHumungus** [comment]
Thanks!
