### ISSUE TITLE
Invalid path parsing

### ISSUE THREAD

**Issue by hyperletter** [Bobris/Nowin#43]
Start nowin sample browse to
http://localhost:8888/Åsna

The decoded URL will be wrong. /Ãsna see the tilde instead of the ring?

**Comment by hyperletter** [comment]
The problem is resolved by
            var result = new string(chs, 0, used);
            byte[] bytes = Encoding.Default.GetBytes(result);
            return Encoding.UTF8.GetString(bytes);

in the ParsePath. Maybe there is a better way to do it, but it seems to fix the problem with UTF-8 escaped paths.

**Comment by Bobris** [comment]
This would be too slow for my taste. Fix/Implementation published in nuget.
