### ISSUE TITLE
Path parsing fails under certain conditions since fixing #43

### ISSUE THREAD

**Issue by pysco68** [Bobris/Nowin#44]
The fix introduced in 8981f8c5e70a87cf9a7a7bf2c43b21e567965d9b makes some previously working queries fail for me. This is because Nowin now decodes the URL patterns like `/pathBase/path?query%20ge` in a way that the `%20` becomes a whitespace. If the application layer expects the non-decoded URL this is a huge problem.

As a test-case take a look at my fork's commit: https://github.com/pysco68/Nowin/commit/2c5d969d605933d4db6a9e05e18d5445b8dfe261

I'm working arround this right now by using the previous version as I didn't have any issue with the UTF8 handling (which wasn't broken to me...)

**Comment by Bobris** [comment]
Ouch sorry, that makes sense.

**Comment by damianh** [comment]
@pysco68 just to mention, the owin spec says the server MUST decode the url http://owin.org/html/spec/owin-1.0.html#55-percent-encoding

**Comment by Bobris** [comment]
This was about query part which actually need to stay encoded.
