### ISSUE TITLE
Not support custom 500 Internal Server Error

### ISSUE THREAD

**Issue by comphilip** [Bobris/Nowin#46]
### Sample Server Code
```C#
class Program {
		static void Main(string[] args) {
			var options = new StartOptions {
				ServerFactory = "Nowin",
				Port = 8080
			};

			using (WebApp.Start<Startup>(options)) {
				Console.WriteLine("Running a http server on port 8080");
				Console.ReadKey();
			}
		}
	}

	public class Startup {
		public void Configuration(IAppBuilder app) {
			app.Use(async (context, task) => {

				context.Response.StatusCode = 500;

				if (context.Request.Path.Value == "/") {
					context.Response.ContentType = "text/plain";
					await context.Response.WriteAsync("Test custom 500 internal error!");
				}
			});
		}
	}
}
```

### Expected Result
* Response status code: 500
* Response Content-Type header value: text/plain
* Response body: Test custom 500 internal error!

### Actual Http Traffic Capture
```
GET http://localhost:8080/ HTTP/1.1
User-Agent: Fiddler
Host: localhost:8080


HTTP/1.1 500 Internal Server Error
Server: Nowin
Date: Fri, 18 Sep 2015 07:34:46 GMT
Content-Length: 0



```

### Caused By
Transport2HttpHandler.cs override response when status code equals 500
```C#
// line 1287
if (_statusCode == 500 || _cancellation.IsCancellationRequested)
{
	_cancellation.Cancel();
	if (!_responseHeadersSend)
		SendInternalServerError(); //override response
	else
	{
		_isKeepAlive = false;
		if (_statusCode == 500)
		{
			SendHttpResponseAndPrepareForNext();
			return;
		}
		CloseConnection();
	}
	return;
}
```

**Comment by Bobris** [comment]
It is little bit of feature - I am expecting then you have 500, application is in so bad state that any response is better to ignore ... So I am not sure if or how to change it right now ... Will think about it.

**Comment by Bobris** [comment]
It could possibly leak sensitive information (so look at it also from security point of view)

**Comment by aaasoft** [comment]
I think here should add a config or property to switch user can handle 500 theirself or not.

**Comment by comphilip** [comment]
Another 5xx status code, while according to RFC 7231, they are for specified error cases. I cannot use 4xx because the error is not caused by client request but invalid state of server (like DB connection problem, disk out of usage and any other unexpected exceptions).

In [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.6): Except when responding to a HEAD request, the server should include an entity containing an explanation of the error situation, and indicate whether it is a temporary or permanent condition. Likewise, user agents should display any included entity to the user. These response codes are applicable to any request method.

Workaround is use another 5xx not defined in RFC 7231. User agent should treat undefined 5xx status code as 500.

**Comment by Bobris** [comment]
I think I will force this 500 handling only if you will throw exception from App (and don't catch it). So you will be able to define "catch" middle-ware which can convert it to 500 with custom content.

**Comment by serialseb** [comment]
I'd think you should lay off from anything but catching exceptions and generating 500. In the other scenarios, middlewares can be added easily enough without nowin supporting it

**Comment by comphilip** [comment]
"catch" middle-ware is a good solution. Transport2HttpHandler class still needs changes to support this. Its ResponseFinished method is executed after middlewares.

**Comment by Bobris** [comment]
I will do this after #39. I hope both should be finished over the weekend...
