### ISSUE TITLE
memoryleak when creating and disposing the server a lot

### ISSUE THREAD

**Issue by lanwin** [Bobris/Nowin#48]
Correct me if I am wrong, but the given code fragment should not end in an memory leak. But it leaks 15mb on every loop and does not seems to free it, not event with an GC.Collect();

```csharp
while(true){
   var serverBuilder = new ServerBuilder();
   serverBuilder.SetPort(8081);
   var server = serverBuilder.Start();
   Thread.Sleep(500);
   server.Dispose();
}
```

To give a little bit feedback why I felt onto this. I have an test app for an internal lib which creates and disposes the server every 10 seconds and test if the lib behaves correctly. But since the server leaks memory, it runs not very long.

I dug a little bit into the codebase of Nowin, but I dont saw anything yet which could cause this leak.

**Comment by Bobris** [comment]
I can reproduce leak.
If you don't need default 256 preallocated handlers you can lower memory grow by calling:
                serverBuilder.SetConnectionAllocationStrategy(new ConnectionAllocationStrategy(10, 10, 100, 5));

You can lower it down to 1 connection:
                serverBuilder.SetConnectionAllocationStrategy(new ConnectionAllocationStrategy(1, 0, 1, 0));

**Comment by Bobris** [comment]
Found it and fixed. Didn't know that ConcurrentBag leaks memory if not emptied.

**Comment by lanwin** [comment]
Superb. Thanks for fixing it that fast! Interesting, I also didnt know that.
