### ISSUE TITLE
Force client certificate

### ISSUE THREAD

**Issue by et1975** [Bobris/Nowin#50]
How can I force the client to authenticate with a certificate with Nowin host?
EDIT: I can check "ssl.ClientCertificate", but how do I tell the browser to prompt the user for a certificate? My understanding is it needs to happen during TLS negotiation, not sure I could influence it after the fact (via headers, status codes).

**Comment by et1975** [comment]
Argh, ssl.ClientCertificate is not being set either... let me figure that out.

**Comment by et1975** [comment]
Actually... looking at the code the change might be more involving than I could do :/
the client certificate should be available [here](https://github.com/Bobris/Nowin/blob/master/Nowin/SslTransportHandler.cs#L223) as _ssl.RemoteCertificate, but I have no idea how to propagate it into the OWIN environment from there.

**Comment by Bobris** [comment]
I hope so finished support. Please test if it is ok. After that I will publish new release.

**Comment by et1975** [comment]
Thanks, it works as expected now! You sir, are awesome.

**Comment by Bobris** [comment]
Thanks for confirmation. Now published as 0.19.0
