### ISSUE TITLE
Periodically getting this exception

### ISSUE THREAD

**Issue by andreybalogh** [Bobris/Nowin#53]
Hi - Not really sure what this means - any help would be appreciated.
Thanks
Andy

Exception: 

System.InvalidOperationException: Already receiving or accepting
   at Nowin.SaeaLayerCallback.StartReceive(Byte[] buffer, Int32 offset, Int32 length)
   at Nowin.Transport2HttpHandler.StartNextReceive()
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by Bobris** [comment]
It should never happen ... Can you create simple repro? Or you can enable detailed logging ...
What version of Nowin, what framework, OS version?

**Comment by zegreatclan** [comment]
Hi ! I reproduce it using nowin + nancyFx, I think it appens when chrome aborts requests.

**Comment by andreybalogh** [comment]
Hi - nowin 0.19.0, .net 4.5, windows 7 Pro SP1

The following is a test that reproduces quickly (within the first or second run). 

using System;
using System.Text;
using System.Net.Sockets;
using System.Net;

namespace NowinCancelTest
{
	class Program
	{
		static void Main(string[] args)
		{
			byte[] bytes = Encoding.ASCII.GetBytes(string.Format("OPTIONS /api/v1/sessions/1/ixnetwork/topology/deviceGroup/ethernet/dhcp4client HTTP/1.1{0}Connection: keepalive{1}Cache-Control: no-cache{2}{3}", 
				Environment.NewLine,
				Environment.NewLine,
				Environment.NewLine, 
				Environment.NewLine));

			for (int i = 0; i < 10; i++)
				Request(bytes, false);

			for (int i = 0; i < 2; i++)
				Request(bytes, true);

			for (int i = 0; i < 20; i++)
				Request(bytes, false);

			for (int i = 0; i < 2; i++)
				Request(bytes, true);
		}

		static void Request(byte[] bytes, bool receive)
		{ 
			try
			{
				Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
				socket.Connect(IPAddress.Loopback, 12345);

				if (receive)
				{
					socket.Send(bytes);
					byte[] recvBytes = new byte[32767];
					int count = socket.Receive(recvBytes);
					System.Diagnostics.Debug.WriteLine(Encoding.ASCII.GetString(recvBytes, 0, count));
				}
				else
				{
					socket.BeginSend(bytes, 0, bytes.Length, SocketFlags.None, null, null);
				}

				socket.Shutdown(SocketShutdown.Both);
				socket.Close();
				socket = null;
			}
			catch(Exception e)
			{
				System.Diagnostics.Debug.WriteLine(e.ToString());
			}
		}
	}
}

**Comment by Bobris** [comment]
Thanks for repro, will try to investigate tomorrow...

**Comment by AdamBurgess** [comment]
Also happening for me (I'm using Heroku)

**Comment by Bobris** [comment]
I can reproduce it and working on fix ... It is very complex to synchronize all these async operations happening in parallel in multiple threads... Actually I have code which does not show problem, but it regressed one test (only in release, not in debug :-( )

**Comment by Bobris** [comment]
Published in nuget as 0.20.0. I cannot reproduce problem anymore even after 10 minutes of run of provided test. Also all tests passing repeatedly without problems.
