### ISSUE TITLE
Nowin doesn't (seem) to automatically urldecode the request url

### ISSUE THREAD

**Issue by Erwinvandervalk** [Bobris/Nowin#57]
If I use nowin to host an application, that also uses webapi, then routeparameters and querystring parameters are not automatically decoded. 

This appears to be different behavior than we get from the microsoft owin selfhost or from our unit tests (which test the owin pipeline without a webserver). 

What's the behavior? if we issue a http request with url encoded parameters (IE: /api/path?param=thisIsAnEncoded%23Hastag, then in webapi, this parameter is still encoded (it still has the %23 in it). 

But in our unit tests, OR if I run in the owin selfhost, I get the decoded value (with a # in it). 

Is this behavior by design?

**Comment by Erwinvandervalk** [comment]
Would this be the place to add url encoding? https://github.com/Bobris/Nowin/blob/master/Nowin/Transport2HttpHandler.cs#L131 If so, I can send you a PR

**Comment by damianh** [comment]
http://owin.org/html/spec/owin-1.0.html#55-percent-encoding

 - The server MUST provide percent-decoded values for "owin.RequestPath" and "owin.RequestPathBase".

 - The server MUST provide a percent-encoded value for "owin.RequestQueryString"

**Comment by damianh** [comment]
@Bobris I think it would be nice to have a `nowin.RequestRawUrl` key too. I can see some scenarios where that would be useful. I'll propose a 'owin.ReqeuestRawUrl` separately.

**Comment by Bobris** [comment]
I think I have by owin spec and there are people like #44 depending on it (when I once break it). Now there are tests covering these ...
@damianh It is currently against my priority for speed. It would need additional allocation and memory copy per request. But if that will be requested by more people I will add it.
