### ISSUE TITLE
是否有新版本更新？

### ISSUE THREAD

**Issue by chenzuo** [Bobris/Nowin#64]
你好，是否有新版本更新呢？

**Comment by Bobris** [comment]
Please write in English.

**Comment by chenzuo** [comment]
Hello, is there a new version of the update do? Are there plans to add new features?   from google Translate  :)

**Comment by Bobris** [comment]
Nowin currently has lowest priority of all my OSS projects. Mainly because I expecting Kestrel will be able to replace it soon.
