### ISSUE TITLE
Nowin implements IOwinRequest.Body.Length incorrectly

### ISSUE THREAD

**Issue by tomasdeml** [Bobris/Nowin#67]
`IOwinRequest.Body` stream in Nowin, backed by the `ReqRespStream` class, does not implement the `Length` property correctly with regard to the value of the `CanSeek` property. [MSDN docs](https://msdn.microsoft.com/cs-cz/library/system.io.stream.canseek(v=vs.110).aspx) have this note in `Stream.CanSeek`:

> If a class derived from Stream does not support seeking, calls to Length, SetLength, Position, and Seek throw a NotSupportedException.

Nowin returns value of `Content-Length` header instead. Kestrel on the other hand [throws NotSupportedException correctly](https://github.com/aspnet/KestrelHttpServer/blob/master/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameRequestStream.cs#L28) (PR aspnet/KestrelHttpServer#256). 

The violation of contract for `IOwinRequest.Body.Length` makes it difficult to host same OWIN middleware on both Nowin and Kestrel - their behavior is not same.

**Comment by Bobris** [comment]
This is breaking change. Will do it after one week, if nobody will oppose this change. Main reason I really want to people prepare for migration to Kestrel.
