### ISSUE TITLE
keep-alive never used

### ISSUE THREAD

**Issue by arakis** [Bobris/Nowin#74]
While debugging with a proxy, i see that "connection: keep-alive" or "connection: close" is never written. It seems, the problem is in this line:
https://github.com/Bobris/Nowin/blob/master/Nowin/Transport2HttpHandler.cs#L621

```csharp
            if (_isHttp10 && _isKeepAlive)
            {
                HeaderAppend("Connection: keep-alive\r\n");
            }
```
_isHttp10 is false, because it's http 1.1, so it will never run the if-block.

removing the "_isHttp10" seems to work (Header is written), but i'm not sure if all other works correct with this change.

**Comment by Bobris** [comment]
By spec it does not need to be there because it is default:
https://stackoverflow.com/questions/7927566/is-an-http-1-1-request-implicitly-keep-alive-by-default?rq=1
